version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: muro_sinav_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: muro_sinav
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
